apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanage-app-deployment
  labels:
    app: usermanage-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermanage-app
  template:
    metadata:
      labels:
        app: usermanage-app
    spec:
      containers:
      - name: usermanage-app
        image: ravik9410/usermanage-service
        ports:
        - containerPort: 80